{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: critic-backend
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "critic.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "critic.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.imageTag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.backend.springProfiles }}"
            - name: SPRING_CONFIG_IMPORT
              value: "configtree:/etc/secrets/"
            - name: POSTGRES_HOST
              value: "critic-postgresql"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.primary.service.ports.postgresql }}"
            - name: POSTGRES_ADMIN_USERNAME
              value: "postgres"
            - name: POSTGRES_USER_USERNAME
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: MINIO_HOST
              value: "critic-minio"
            - name: MINIO_PORT
              value: "{{ .Values.minio.service.port }}"
            - name: MOCKER_HOST
              value: "critic-mocker"
            - name: MOCKER_PORT
              value: "{{ .Values.mocker.service.port }}"
          volumeMounts:
            - name: secrets-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets-volume
          projected:
            sources:
              - secret:
                  name: critic-backend-secret
              - secret:
                  name: critic-postgres-secret
              - secret:
                  name: critic-redis-secret
              - secret:
                  name: critic-minio-secret
                  items:
                    - key: rootUser
                      path: MINIO_ADMIN_USERNAME
                    - key: rootPassword
                      path: MINIO_ADMIN_PASSWORD
{{- end }}
