{{- if and .Values.secrets .Values.secrets.twilioAccountSid .Values.secrets.twilioAuthToken .Values.secrets.twilioServiceSid .Values.secrets.rsaPublicKey .Values.secrets.rsaPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: critic-backend-secret
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilioAccountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilioAuthToken | quote }}
  TWILIO_SERVICE_SID: {{ .Values.secrets.twilioServiceSid | quote }}
  RSA_PUBLIC_KEY: {{ .Values.secrets.rsaPublicKey | quote }}
  RSA_PRIVATE_KEY: {{ .Values.secrets.rsaPrivateKey | quote }}
{{- end }}
{{- if and .Values.secrets .Values.secrets.minioAdminUser .Values.secrets.minioAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: critic-minio-secret
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.secrets.minioAdminUser | quote }}
  rootPassword: {{ .Values.secrets.minioAdminPassword | quote }}
{{- end }}
{{- if and .Values.secrets .Values.secrets.postgresAdminPassword .Values.secrets.postgresUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: critic-postgres-secret
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_ADMIN_PASSWORD: {{ .Values.secrets.postgresAdminPassword | quote }}
  POSTGRES_USER_PASSWORD: {{ .Values.secrets.postgresUserPassword | quote }}
{{- end }}
{{- if and .Values.secrets .Values.secrets.redisAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: critic-redis-secret
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_ADMIN_PASSWORD: {{ .Values.secrets.redisAdminPassword | quote }}
{{- end }}
{{- if and .Values.secrets .Values.secrets.grafanaAdminUser .Values.secrets.grafanaAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: critic-grafana-secret
  labels:
    {{- include "critic.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  GRAFANA_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
{{- end }}
