spring:
  config:
    activate:
      on-profile: prod
  datasource:
    jdbc: postgresql://rateit-postgresql:5432/postgres
  cloud:
    aws:
      s3:
        endpoint: http://${MINIO_HOST:rateit-minio}:${MINIO_PORT:9000}

security:
  auth:
    cookie:
      secure: true

logging:
  level:
    root: INFO
